name: "Terraform Apply"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  apply:
    name: "Apply Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: |
          git config --global url."https://oauth2:${{ secrets.GIT_HUB_TOKEN }}@github.com".insteadOf https://github.com
          terraform init

      - name: Terraform Apply
        run: terraform apply